name: Release to PyPI

on:
  push:
    branches:
      - 'main' # Trigger on main branch

jobs:
  pypi-test-build-and-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags') # Trigger on tags only on main branch
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Build
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publish distribution 📦 to PyPI
        if: ${{ !contains(github.ref, 'dev') }}
        uses: pypa/gh-action-pypi-publish@release/v1
