name: Test Knapsack

on: push

jobs:
  test_knapsack:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/prod.txt

    - name: Copy tests
      run: cp tests/tests.py .
    
    - name: Run knapsack test
      run: |
        python tests.py knapsack > actual_output.txt
        diff -u tests/outputs/knapsack.txt actual_output.txt || (echo "::error::Output does not match expected." && exit 1)

    - name: Run tsp test
      run: |
        python tests.py tsp > actual_output.txt
        diff -u tests/outputs/tsp.txt actual_output.txt || (echo "::error::Output does not match expected." && exit 1)
